# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0a4595e66713480a7f681582bb90ec5d64775c51877c6cc11d43bd5f652f5b897883449fa5b4ed9c894ea1346423230f153d1c60ec0fa44b5a345812d911366

test:
  secret_key_base: 2926b2aff8c3c43db38a2ab34b4034e496c9f95f929b68eb4adad758ed35787cdc7f7c238fa47794ec9a19f2451f9bc6eca1cea08d5635a391d21fec2532248d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
